Update build-kernel-release.yml

diff --git a/.github/workflows/build-kernel-release.yml b/.github/workflows/build-kernel-release.yml
--- a/.github/workflows/build-kernel-release.yml
+++ b/.github/workflows/build-kernel-release.yml
@@ -65,7 +65,203 @@ jobs:
             branch: oneplus/sm8550
             manifest: oneplus_11_v.xml
             android_version: android13
-            kernel_version: "5.15"
+            kernel_version: '5.15'
+          - model: OP12
+            soc: pineapple
+            branch: oneplus/sm8650
+            manifest: oneplus12_v.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP13
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_13.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OP-PAD-3
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_pad_3.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OP-OPEN
+            soc: kalama
+            branch: oneplus/sm8550
+            manifest: oneplus_open_v.xml
+            android_version: android13
+            kernel_version: '5.15'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Select Appropriate SusFS Branch
+        id: get-susfs-branch
+        run: |
+          KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
+          
+          SUSFS_BRANCH=""
+
+          case "$KERNEL_STRING" in
+            "android12-5.10")
+              SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch_or_commit }}"
+              ;;
+            "android13-5.10")
+              SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch_or_commit }}"
+              ;;
+            "android13-5.15")
+              SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch_or_commit }}"
+              ;;
+            "android14-5.15")
+              SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch_or_commit }}"
+              ;;
+            "android14-6.1")
+              SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch_or_commit }}"
+              ;;
+            "android15-6.6")
+              SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch_or_commit }}"
+              ;;
+            *)
+              echo "Invalid kernel version or unsupported: $KERNEL_STRING"
+              exit 1
+              ;;
+          esac
+          
+          echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT
+
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Build Kernel
+        uses: WildKernels/OnePlus_KernelSU_SUSFS/.github/actions@main
+        with:
+          model: ${{ matrix.model }}
+          soc: ${{ matrix.soc }}
+          branch: ${{ matrix.branch }}
+          manifest: ${{ matrix.manifest }}
+          ksun_branch: ${{ inputs.ksun_branch }}
+          susfs_commit_hash_or_branch: ${{ steps.get-susfs-branch.outputs.susfs_branch }}
+          optimize_level: ${{ inputs.optimize_level }}
+
+  build-batch-2:
+    name: build-batch-2 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ matrix.branch }}, ${{ matrix.manifest }}, ${{ matrix.android_version }}, ${{ matrix.kernel_version }}, ${{ inputs.ksun_branch }})
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - model: OP13r
+            soc: pineapple
+            branch: oneplus/sm8650
+            manifest: oneplus_13r.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP-NORD-4
+            soc: pineapple
+            branch: oneplus/sm7675
+            manifest: oneplus_nord_4_v.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP-Nord-5
+            soc: cliffs
+            branch: oneplus/sm8635
+            manifest: oneplus_nord_5.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP-PAD-2
+            soc: pineapple
+            branch: oneplus/sm8650
+            manifest: oneplus_pad2_v.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP-Nord-CE4-LITE
+            soc: blair
+            branch: oneplus/sm6375
+            manifest: oneplus_nord_ce4_lite_5g_v.xml
+            android_version: android14
+            kernel_version: '6.1'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Select Appropriate SusFS Branch
+        id: get-susfs-branch
+        run: |
+          KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
+          
+          SUSFS_BRANCH=""
+
+          case "$KERNEL_STRING" in
+            "android12-5.10")
+              SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch_or_commit }}"
+              ;;
+            "android13-5.10")
+              SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch_or_commit }}"
+              ;;
+            "android13-5.15")
+              SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch_or_commit }}"
+              ;;
+            "android14-5.15")
+              SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch_or_commit }}"
+              ;;
+            "android14-6.1")
+              SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch_or_commit }}"
+              ;;
+            "android15-6.6")
+              SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch_or_commit }}"
+              ;;
+            *)
+              echo "Invalid kernel version or unsupported: $KERNEL_STRING"
+              exit 1
+              ;;
+          esac
+          
+          echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT
+
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Build Kernel
+        uses: WildKernels/OnePlus_KernelSU_SUSFS/.github/actions@main
+        with:
+          model: ${{ matrix.model }}
+          soc: ${{ matrix.soc }}
+          branch: ${{ matrix.branch }}
+          manifest: ${{ matrix.manifest }}
+          ksun_branch: ${{ inputs.ksun_branch }}
+          susfs_commit_hash_or_branch: ${{ steps.get-susfs-branch.outputs.susfs_branch }}
+          optimize_level: ${{ inputs.optimize_level }}
+
+  build-batch-3:
+    name: build-batch-3 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ matrix.branch }}, ${{ matrix.manifest }}, ${{ matrix.android_version }}, ${{ matrix.kernel_version }}, ${{ inputs.ksun_branch }})
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - model: OP11r
+            soc: waipio
+            branch: oneplus/sm8475
+            manifest: oneplus_11r_v.xml
+            android_version: android12
+            kernel_version: '5.10'
+          - model: OP10t
+            soc: waipio
+            branch: oneplus/sm8475
+            manifest: oneplus_10t_v.xml
+            android_version: android12
+            kernel_version: '5.10'
+          - model: OP-Nord-4-CE
+            soc: crow
+            branch: oneplus/sm7550
+            manifest: oneplus_nord_ce4_v.xml
+            android_version: android13
+            kernel_version: '5.15'
+          - model: OP10pro
+            soc: waipio
+            branch: oneplus/sm8450
+            manifest: oneplus_10_pro_v.xml
+            android_version: android12
+            kernel_version: '5.10'
+          - model: OP12r
+            soc: kalama
+            branch: oneplus/sm8550
+            manifest: oneplus_12r_v.xml
+            android_version: android13
+            kernel_version: '5.15'
     runs-on: ubuntu-latest
     steps:
       - name: Select Appropriate SusFS Branch
@@ -119,6 +315,8 @@ jobs:
   trigger-release:
     needs:
       - build-batch-1
+      - build-batch-2
+      - build-batch-3
     runs-on: ubuntu-latest
     if: ${{ inputs.make_release }}
     env:
@@ -146,7 +344,7 @@ jobs:
         [+] Manual Hooks [scope_min_manual_hooks_v1.4]
         [+] CONFIG_TMPFS_XATTR Support [Mountify Support]
         [+] BBR v1 Support.
-        [+] HMBIRD scx support for OnePlus 13 & OnePlus Ace 5 Pro.
+        [+] HMBIRD scx support for OnePlus 13
 
     steps:
       - name: Checkout code
